# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/finlog_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:123456}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent}
