#Conexão com MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/finlog_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

#Sincronização de Tabelas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração da IA (Gemini)
gemini.api.key=${GEMINI_API_KEY}
# Versão estável e URL atualizada
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent